title: Let People Work
title_separator: "|"

email: contact@letpeople.work
description: >- # this means to ignore newlines until "baseurl:"
  It is getting harder and harder for us to focus on our work. Monotonous interactions and recurring meetings keep us busy as well as distracted from what should be our focus: delivering value to our customers.
  As we go on, more meetings are added to rectify the situation, more things are "high-priority" and even less gets done.
  The result? Frustrated team members, overwhelmed managers, angry stakeholders, and complaining customers.
  People want to contribute. People want to deliver value. People want to be part of something successful. We just need to let them work.
  We've seen what impact a change in the system can have on individuals, teams, as well as an organization as a whole.
  We at Let People Work would like to support you in unleashing the full potential of your employees and teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

minimal_mistakes_skin: "dark" # options: default, air, aqua, contrast, dark, dirt, mint, neon, plum, sunrise
locale: "en-US"

search: false
github_username:  letpeoplework
repository: "letpeoplework/letpeoplework.github.io"
logo: "/assets/Logo.png"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache


include: ["_pages"]

footer:
  links:
    - label: "Calendly"
      icon: "fa-solid fa-phone"
      url: "https://calendly.com/letpeoplework/"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:contact@letpeople.work"
    - label: "Slack"
      icon: "fab fa-fw fa-slack"
      url: "https://join.slack.com/t/let-people-work/shared_invite/zt-2y0zfim85-qhbgt8N0yw90G1P~JWXvlg"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/let-people-work"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/letpeoplework"    